### PR TITLE
Fix 'TypeError: options argument must be an object' error due to spawn() changes

### LINKED ISSUE #13: Speakable fails on Node.js v4.2.1 due to spawh() changes
Running speakable on Node.js v4.2.1 fails with `[TypeError: options argument must be an object]`. This happens when trying to spawn the `sox` process ([node-speakable.js, line 75](https://github.com/sreuter/node-speakable/blob/master/lib/node-speakable.js#L75)) due to the options argument passed being a string.

The quick fix for this is to change that line to 

`var rec = spawn(self.cmd, self.cmdArgs, {stdio:'pipe'});`

I haven't tested this change on Node.js v0.12.x though.

### LINKED ISSUE #15: Error Message on MacBook
I am using a Mac with the latest OS.

I downloaded the module and I put the sox binary into the lib folder. But I am continuing to get this error (in the screenshot):

screen shot 2016-02-07 at 5 41 13 pm

I havent changed the code because I have just been trying to get it to work on my machine. I also tried the same test on my Windows machine, and put the SoX windows binary instead but got the same error.

my code is here:

https://github.com/gcrev93/FrozenBot

can anyone tell me what is causing this error?

### PR DESCRIPTION
**Pull request by Jamil**
This small change fixes #13 and fixes #15 (which is a dupe). I've tested on node/0.12.7 and node/5.7.0 and it seems to work on both.

### CODE REVIEW

**Comment by joestrong** [comment]
Thank you :+1:

**Comment by sixtop** [comment]
Thank you Jamil... Can we merge this fix?

**Comment by Jamil** [comment]
@sixtop We'll have to ask @sreuter to merge since I don't have permission

**Comment by sreuter** [comment]
@Jamil @joestrong @sixtop Sorry for the delay, somehow I don't get notification for PRs for a while. I'll check my settings ;)

**Pull request merged**
